name: AndroidBuild

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip zipalign
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-34" "build-tools;34.0.0"
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create local.properties
        run: echo "sdk.dir=$HOME/android-sdk" > local.properties

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Sign Release APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA256 -keystore ${{ github.workspace }}/keystore/CICD.jks -storepass ${{ secrets.CICD_KEYSTORE_PASSWORD }} app/build/outputs/apk/release/app-release-unsigned.apk cicd
          zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-signed.apk

      - name: Upload Signed Release APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Release-APK
          path: app/build/outputs/apk/release/app-release-signed.apk

      - name: Build Release App Bundle
        run: ./gradlew bundleRelease

      - name: Sign Release App Bundle
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA256 -keystore ${{ github.workspace }}/keystore/CICD.jks -storepass ${{ secrets.CICD_KEYSTORE_PASSWORD }} app/build/outputs/bundle/release/app-release.aab cicd

      - name: Upload Signed Release App Bundle
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Release-App-Bundle
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Install Zipalign
        run: sudo apt-get install zipalign
